signed_32bit_constant = "константа размером 32 бит, знаковое целое число (int 32)"
unsigned_32bit_variable = "переменная размером 32 бит, беззнаковое целое число (unsigned int 32)"
explicit_coercion = "@as производит явное приведение типов"
