name: push_on_master
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  pr:
    runs-on: ubuntu-latest
    outputs:
      pr_found: ${{ steps.pr.outputs.pr_found }}
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pr
  test:
    strategy:
      matrix:
        # disabling windows-latest for now. zig fmt --check gives strange results
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          # run tests only if this is direct push to master
          # because if from pr, then tests are already run
          if [ -z "${{ needs.pr.outputs.pr_found }}" == 'false' ]; then
            zig run test-out.zig
            zig test do_tests.zig
            zig fmt --check test-out
          fi
  mkdocs-gh-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
