name: push_on_master_without_pr
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  test:
    # prevent running this job if it is from direct push, not from pull request
    # this will still show the workflow and skipped job in the ui.
    # there is no way currently to not trigger workflow on direct push
    # oter than Server-side Git Hook
    if: github.event.before == github.event.after
    strategy:
      matrix:
        # disabling windows-latest for now. zig fmt --check gives strange results
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          zig run test-out.zig
          zig test do_tests.zig
          zig fmt --check test-out
  mkdocs-gh-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
